# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_DEPLOY: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  deploy_pipeline:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm install

      - name: Build
        id: build
        run: npm run build

      - name: Deploy
        id: deploy
        run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOY == 'false' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Discord Notify Build Failure
        if: ${{ failure() && steps.build.outcome == 'failure' }}
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'GitHub'
          DISCORD_AVATAR: 'https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png'
          DISCORD_EMBEDS: >-
            [{
              "title": "Pokedex Build Failure",
              "color": 16711680,
              "description": "Build failed.",
              "fields": [
                { "name": "URL", "value": "${{ github.event.head_commit.url }}" }
              ]
            }]

      - name: Discord Notify Deploy Failure
        if: ${{ failure() && steps.deploy.outcome == 'failure' }}
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'GitHub'
          DISCORD_AVATAR: 'https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png'
          DISCORD_EMBEDS: >-
            [{
              "title": "Pokedex Deployment Failure",
              "color": 16711680,
              "description": "Deployment failed.",
              "fields": [
                { "name": "Commit", "value": "${{ github.event.head_commit.url }}" }
              ]
            }]

      - name: Discord Notify Deploy Success
        if: ${{ success() && steps.deploy.outcome == 'success' }}
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'GitHub'
          DISCORD_AVATAR: 'https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png'
          DISCORD_EMBEDS: >-
            [{
              "title": "Pokedex Successfully Deployed",
              "color": 6749952,
              "description": "Successful new deployment.",
              "fields": [
                { "name": "Commit", "value": "${{ github.event.head_commit.url }}" }
              ]
            }]

  tag_release:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    needs: [deploy_pipeline]
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Push tag
        id: tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOY == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  ping_fly:
    name: ping
    runs-on: ubuntu-latest
    needs: [deploy_pipeline]
    concurrency: deploy-group
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check deployment health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-proud-silence-5787.fly.dev/nothealth
          max-attempts: 3
          retry-delay: 10s
