name: Health Check Ping

on:
  schedule:
    - cron: '45 * * * *'

jobs:
  ping_fly:
    name: ping
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check deployment health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-proud-silence-5787.fly.dev/health
          max-attempts: 3
          retry-delay: 10s
